version: '3.1'

services:

    wildfly:
      build:
        context: .
        args:
          DB_HOST: db
          DB_NAME: sulfur
          DB_USER: sulfur_user
          DB_PASS: sulfur_pass
          LOGSTASH_HOST: logstash
      environment:
        DB_HOST: db
        DB_NAME: sulfur
        DB_USER: sulfur_user
        DB_PASS: sulfur_pass
        LOGSTASH_HOST: logstash
      ports:
        - 127.0.0.1:8080:8080
        - 127.0.0.1:9990:9990
      links:
        - db
      volumes:
        - ./target/sulfur.war:/opt/jboss/wildfly/standalone/deployments/sulfur.war

    db:
        image: postgres
        restart: always
        environment:
            POSTGRES_USER: sulfur_user
            POSTGRES_PASSWORD: sulfur_pass
            POSTGRES_DB: sulfur

    adminer:
        image: adminer
        restart: always
        ports:
            - 8081:8080