version: '3.1'

services:

    wildfly:
      image: potassium-backend
      build: .
      environment:
        DB_HOST: db
        DB_NAME: potassium
        DB_USER: potassium_user
        DB_PASS: potassium_pass
        LOGSTASH_HOST: logstash
        ZOHO_MAIL_FROM: prueba@magnesium.coop
        ZOHO_MAIL_PASS: prueba
        ROOT_PASSWORD: prueba
      ports:
        - 127.0.0.1:8080:8080
        - 127.0.0.1:9990:9990
      links:
        - db
      volumes:
        - ./resources/deployments:/opt/jboss/wildfly/standalone/deployments

    db:
        image: postgres
        environment:
            POSTGRES_USER: potassium_user
            POSTGRES_PASSWORD: potassium_pass
            POSTGRES_DB: potassium

    adminer:
        image: adminer
        links:
                - db
        ports:
            - 8081:8080